pipeline {
  environment {
    //PROJECT = "REPLACE_WITH_YOUR_PROJECT_ID"
	PROJECT = "teak-sunup-382719"
    APP_NAME = "binary-calculator2"
	//CLUSTER = "REPLACE_WITH_YOUR_CLUSTER_NAME"
    CLUSTER = "sofe3980u"
    CLUSTER_ZONE = "northamerica-northeast1-b"
    IMAGE_TAG = "gcr.io/${PROJECT}/${APP_NAME}"
    JENKINS_CRED = "teak-sunup-382719"
  }
  
agent {
    kubernetes {
	label 'topology.gke.io/zone=northamerica-northeast1-b'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  # Use service account that can deploy to all namespaces
  serviceAccountName: cd-jenkins
  containers:
  - name: gcloud
    image: gcr.io/cloud-builders/gcloud
    //image: google/cloud-sdk:latest
    command:
    - cat
    tty: true
  - name: kubectl
    image: gcr.io/cloud-builders/kubectl
    command:
    - cat
    tty: true
"""
}
  }
  tools {
    maven 'maven' 
  }
  stages {
    stage ('Init') {
      steps {
	    checkout scm
        sh 'echo "Start of Job"'
      }
    }
    //stage ('test') {
    //  steps {
    //    sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
    //  }
    //}
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage('Build and push image with Container Builder') {
      steps {
        container('gcloud') {
	  sh "/builder/google-cloud-sdk/bin/gcloud auth activate-service-account jenkins-sa@teak-sunup-382719.iam.gserviceaccount.com --key-file=./teak-sunup-382719-3a82ef1891e7.json --project=teak-sunup-382719"
          sh "/builder/google-cloud-sdk/bin/gcloud builds submit -t ${IMAGE_TAG} ./BinaryCalculatorWebapp/"
        }
      }
    }
  }
}
